#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)

-include ../config/make.cfg
-include ../config/saga.config.python.c.mk

SAGA_SUBDIRS  += python

include $(SAGA_MAKE_INCLUDE_ROOT)/saga.mk

