#  Copyright (c) 2010 Ole Weidner (oweidner@cct.lsu.edu)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)

SAGA_PYTHON_ROOT = ../

SAGA_SUBDIRS     = apidocs

-include $(SAGA_PYTHON_ROOT)/config/make.cfg
-include $(SAGA_MAKE_INCLUDE_ROOT)/saga.mk

